"""Criando Migrations

Revision ID: d0b53ce5d494
Revises: 
Create Date: 2024-09-04 20:46:15.794895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b53ce5d494'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cargos_id', table_name='cargos')
    op.drop_index('ix_cargos_nome', table_name='cargos')
    op.drop_table('cargos')
    op.drop_index('ix_funcionario_id', table_name='funcionario')
    op.drop_index('ix_funcionario_nome', table_name='funcionario')
    op.drop_table('funcionario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('datanascimento', sa.DATE(), nullable=True),
    sa.Column('cod_cargo', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_funcionario_nome', 'funcionario', ['nome'], unique=False)
    op.create_index('ix_funcionario_id', 'funcionario', ['id'], unique=False)
    op.create_table('cargos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cargos_nome', 'cargos', ['nome'], unique=1)
    op.create_index('ix_cargos_id', 'cargos', ['id'], unique=False)
    # ### end Alembic commands ###
